#!/usr/bin/env python

# ==== MADMAN Team =====

from munin.mongodb import MuninMongoPlugin


class MongoConnectPlugin(MuninMongoPlugin):
    title = "MongoDB current connections"
    args = "-l 0 --base 1000"
    vlabel = "connections"
    info = "MongoDB current connections"
    fields = (
        ('current', dict(
            label="connections",
            info="MongoDB current connections",
            type="COUNTER",
            min="0",
            draw="LINE1",
        )),
    )

    def execute(self):
        status = self.server_status
        try:
            value = status["connections"]["current"]
        except KeyError:
            value = "I"
        return dict(current=value)

if __name__ == "__main__":
    MongoConnectPlugin().run()
