#!/usr/bin/python3

# ==== MADMAN Team =====

from munin.mongodb import MuninMongoPlugin


class MongoDBOpsPlugin(MuninMongoPlugin):
    title = "MongoDB operations"
    args = "-l 0 --base 1000"
    vlabel = "ops/sec"
    info = "Operations"
    ops = ("query", "update", "insert", "delete", "command", "getmore")

    @property
    def fields(self):
        return [
            (op, dict(
                label="%s operations" % op,
                info="%s operations" % op,
                type="COUNTER",
                min="0",
                max=500000,
                draw="LINE1"
            )) for op in self.ops
            ]

    def execute(self):
        status = self.server_status
        return dict(
            (op, status["opcounters"].get(op, 0))
            for op in self.ops
        )
if __name__ == "__main__":
    MongoDBOpsPlugin().run()
